### ISSUE TITLE
Url or Attachment Data for Non Image Message Attachments

### ISSUE THREAD

**Issue by rolovilla** [restfb/restfb#250] opened 2015-06-19 19:13 UTC
What if I need the url or data from a message attachment other than a Image, a video or zip file for instance. There is no way to get that as of now in the Message.Attachment class.

**Comment by nbartels** [comment] 2015-06-19 19:37
Can you provide an example JSON. You may obfuscate the object, but the structure should be untouched. So I can change the objects accordingly.

**Comment by rolovilla** [comment] 2015-06-19 19:44
Do you refer to a JSON example as returned by the Graph API or the one I am handling in the Java code? The json attachment returned by the Graph API looks like something like this:
"attachments": {
    "data": [
      {
        "id": "999999999999",
        "mime_type": "video/mp4",
        "name": "myvideofile.mp4",
        "size": 22001
      }
    ]
    }

**Comment by nbartels** [comment] 2015-06-19 21:03
thx. So the attachment information in the graph api reference is correct :)

I'll check this and try to solve the issue in the next release.

**Comment by rolovilla** [comment] 2015-06-19 21:39
The problem is there is not a url or link or even data field anywhere, is this even possible to achieve without the API at least exposing a data field so one can decode it?

**Comment by nbartels** [comment] 2015-06-19 22:10
I googled a bit this issue and it seems that's this is a bit strange. Some people tell about a privacy issue, but I don't understand why (for example) a page should not be able to fetch the attachment with a tool, but via the Facebook UI. 

Perhaps I should create a bug at Facebook and let them explain why I can download an image but not another file.

ATM this is an Facebook issue, so I cannot change it in RestFB :)

**Comment by rolovilla** [comment] 2015-06-19 23:24
Its bug and its reported. https://developers.facebook.com/bugs/153137724878722?browse=external_tasks_search_results_52517d949d48d3494815922
What does Its by Design means? Theres no chance of it changing, like ever?

**Comment by nbartels** [comment] 2015-06-20 14:01
"By Design" means Facebook made this design decision and it is not a bug. The link you gave me is very interesting, because they seem to handle your problem as feature request. So I think I subscribe that issue and close this issue at restfb because atm I cannot do anything. 

As soon as Facebook adds the file information with url to the attachment I'll add it to restfb.

**Comment by nbartels** [comment] 2015-06-30 22:10
Here's my bug report and obviously this is a Change/Feature Request.

https://developers.facebook.com/bugs/1457565967890796

You may subscribe to the Facebook bug and I close this restfb issue.

**Comment by nbartels** [comment] 2015-07-08 08:33
Still open at Facebook, but I close it here to not "pollute" the issues overview

**Closed by nbartels** 2015-07-08 08:33 UTC
Labels: type: Facebook By Design

**Comment by nbartels** [comment] 2015-07-14 07:35
Facebook closed this right now as "won't fix" but they consider this as a future feature request ...
