### ISSUE TITLE
fetchObjects normelizes IDs that are case sensitive

### ISSUE THREAD

**Issue by oferfort** [restfb/restfb#702] opened 2017-03-26 11:33 UTC
In DefaultFacebookClient.fetchObjects there's a section that changes all IDs to lower case.
When trying to fetch a conversation ID that has UPPERCASE chars, it will change to lower and it returns empty while if you keep the casing in tact, it returns a result.

**Comment by nbartels** [comment] 2017-03-26 19:18
Thanks for the information. 

This is a duplicate of #698 .

**Closed by nbartels** 2017-03-26 19:18 UTC
