### ISSUE TITLE
How to get 3 second video views using restfb

### ISSUE THREAD

**Issue by manssa01** [restfb/restfb#832] opened 2017-12-06 14:10 UTC
Hello,
Here is my code, could  you please help:

Ad.APIRequestGetInsightsAsync insightsAsync = new Ad(adId, context).getInsightsAsync();
// AdReportRun report = insightsAsync
//	.requestField("account_name")
//	.requestField("impressions")
// .requestField("spend")
// .requestField("reach")
// .requestField("total_actions")
//	.requestField("clicks")
////	.requestField("total_video_views")
////	.requestField("cpc")
////	.requestField("cost_per_action_type")
////	.requestField("cost_per_unique_click")
////	.requestField("cpm")
// .requestField("video_10_sec_watched_actions")
// .requestField("video_30_sec_watched_actions")
// .requestField("video_p100_watched_actions")
// .requestField("video_p95_watched_actions")
// .requestField("video_p75_watched_actions")
// .requestField("video_p50_watched_actions")
// .requestField("video_p25_watched_actions")
//	.execute()
//	.head();
// while (report.fetch().getFieldAsyncPercentCompletion() != 100) {
//	try {
//	Thread.sleep(6000);
//	} catch (InterruptedException e) {
//
//	}

Thanks and best regards

**Comment by nbartels** [comment] 2017-12-06 14:13
Duplicate of #829

**Closed by nbartels** 2017-12-06 14:13 UTC
Labels: type: duplicate
