### ISSUE TITLE
Unable to fully convert Posts to JSON because of multiple annotations

### ISSUE THREAD

**Issue by tscholak** [restfb/restfb#442] opened 2016-04-21 17:20 UTC
Hi,

I'm running into this problem, https://code.google.com/archive/p/restfb/issues/186, albeit with [[Post]]s.
if a post has many annotations, e.g. of type Like or Location, only one of them is jsonified.

Some relevant code piece is copied here from the restfb sources for convenience:
```
    // No longer throw an exception in this case. If there are multiple fields
    // with the same @Facebook value, it's luck of the draw which is picked for
    // JSON marshaling.
    // TODO: A better implementation would query each duplicate-mapped field. If
    // it has is a non-null value and the other duplicate values are null, use
    // the non-null field.
    Set<String> facebookFieldNamesWithMultipleMappings = facebookFieldNamesWithMultipleMappings(fieldsWithAnnotation);
    if (facebookFieldNamesWithMultipleMappings.size() > 0 && logger.isLoggable(FINE)) {
      logger.fine("Unable to convert to JSON because multiple @" + Facebook.class.getSimpleName()
          + " annotations for the same name are present: " + facebookFieldNamesWithMultipleMappings);
    }
```

Are there any plans to fix this issue?

Cheers

**Comment by nbartels** [comment] 2016-04-21 18:36
Can you please provide a json so I can reproduce and fix this. Thanks

**Comment by nbartels** [comment] 2016-07-19 10:04
I have to close this, because I cannot reproduce it, no Json is provided and the issue is reported only once.

**Closed by nbartels** 2016-07-19 10:04 UTC
Labels: analysis
