### ISSUE TITLE
Get new comments from a page created after an specific date

### ISSUE THREAD

**Issue by CarlosEsquivel** [restfb/restfb#57] opened 2013-04-17 08:02 UTC
Hello,
I need to get new comments from a page created after an specific date.
I used :
```java
Connection<Comment> myFeed = client.fetchConnection("page/feed", Comment.class, new Parameter[] { Parameter.with("since", date) });
```

But this doesn't return the desired results.

How could we build the filter for those new comments? Can we get posts from its update time?

Thanks.

**Comment by nbartels** [comment] 2015-02-14 15:52
Interesting question, but I have no answer to this atm. If you find a solution, that doesn't contain the usage of the [realtime updates](https://developers.facebook.com/docs/graph-api/real-time-updates/v2.2), I'd like to hear it :smile:

**Comment by nbartels** [comment] 2015-07-08 08:32
Moved to the Facebook By Design milestone and close this issue, because we cannot do anything about it. it's a decision Facebook made.

**Closed by nbartels** 2015-07-08 08:32 UTC
Labels: type: Facebook By Design
