### ISSUE TITLE
Repeated messages from Facebook Message

### ISSUE THREAD

**Issue by johngardenghi** [restfb/restfb#614] opened 2016-11-05 15:50 UTC
We are experiencing an issue that we are not sure the origin of it.

The problem is with the Messenger Platform. When we send a message from facebook, our client receives two or more JSON packages, changing just the "time" field of the message. But the biggest problem is that this issue is intermitent. Do you know if it is an issue of Facebook Message API or of RestFB?

**Comment by nbartels** [comment] 2016-11-05 22:06
Please check this Facebook Bug, perhaps it is your issue: https://developers.facebook.com/bugs/539811979555488/

If Facebook sends for one message several jsons it is a Facebook problem. RestFB can only react and parse the data sent by Facebook.

**Comment by johngardenghi** [comment] 2016-11-06 00:39
Thanks very much!

Just like I was thinking... The unique difference in my case is that the
fields "mid" and "seq" from message json are the same in the multiple post
requests from Facebook, but timestamp is usually different, except
sometimes when I receive two identical messages at the same time.

Em 5 de nov de 2016 20:06, "Norbert Bartels" <notifications@github.com>
escreveu:

**Comment by nbartels** [comment] 2016-11-07 08:25
I close this and move it to the Facebook By Design milestone, but You may add some news regarding the problem (or a bug id if you open one). Perhaps this is helpful for someone ;)

**Closed by nbartels** 2016-11-07 08:25 UTC
Labels: type: question
