### ISSUE TITLE
Uploading an AdImage

### ISSUE THREAD

**Issue by EZWrighter** [restfb/restfb#332] opened 2015-11-20 22:00 UTC
Failure when attempting to upload an image to an AdAccount.  I did not see any specific documentation on this @ restfb, but thought it might be possible by using the client publish method of restfb.

https://developers.facebook.com/docs/marketing-api/reference/ad-image#Creating

I attempted a couple different routes to try and complete this.  Initially I attempted a zipbytes parameter with the publish method:

GraphResponse response = facebookClient.publish("/{AdAccountId}/adimages", GraphResponse.class,				Parameter.with("zipbytes", new String(zipBytes, "UTF-8")));

Which threw NO exceptions, but returned a GraphResponse with isSuccess() == false and the file was NOT added to the Ad Account.

Then I attempted with "bytes" parameter

GraphResponse response = facebookClient.publish("/{AdAccountId}/adimages", GraphResponse.class,
				  Parameter.with("bytes", new String(fileBytes, "UTF-8")));

and received an exception: Received Facebook error response of type FacebookApiException: Invalid parameter (code 100, subcode 1487242)

Am I doing this all wrong?  Is this even possible with the current code base?  I did successfully upload a video to the ad account, so I couldn't image that this would be a more difficult process :-)

Thanks for any pointers.

**Comment by nbartels** [comment] 2015-11-20 22:32
1. The `zipbytes` example
Can you please try the "NO exception" case again and let the Response be a `JsonObject` instead of the `GraphResponse`, because the Facebook documentation says the request would return a `Map`.

> Return Type (from https://developers.facebook.com/docs/marketing-api/reference/ad-image#Creating) 
 ```java
Map {
     string: Map {
          string: Struct {
               hash: string,
               url: string,
          }
     }
}
```

2. The `bytes` example
In this case you should try to use the `BinaryAttachment` instead of the normal `Parameter`. For an example you should have a look at the documentation: http://restfb.com/#publishing-photo

**Comment by EZWrighter** [comment] 2015-11-20 23:00
Thanks for the fast response.

> Can you please try the "NO exception" case again and let the Response be a JsonObject instead of the GraphResponse

I did this and the JSON response was an empty json object "{}"

I also tried the call with a Binary Attachment:

```Java
JsonObject response = facebookClient.publish("/{AdAccountId}/adimages", JsonObject.class,
				  BinaryAttachment.with("bytes", fileBytes));
```

and receive an Exception:  `FacebookApiException: Invalid parameter (code 100, subcode 1487411)`

Appreciate the help.

**Comment by EZWrighter** [comment] 2015-11-21 00:04
Alright, I figured it out by "Hack and Guess".  Looks like facebook forgot a major piece of documentation in the adimage create.  You need to Base64 Encode the data and then UTF-8 encode it.  This works to upload a zipped adimage:

```Java
facebookClient.publish("/{AdAccountId}/adimages", JsonObject.class, Parameter.with("zipbytes", new String(Base64.encodeBase64(fileBytes), "UTF-8")));
```
I will post a bug report with facebook on their API docs.

**Comment by nbartels** [comment] 2015-11-21 10:20
Thanks, great! 

What about the `bytes` way. Does it work with a Base64 encoded file data?

BTW in the "creating" documentation they say something about an example, but I cannot find it. So this should be linked or added :smile: I add this as FB documentation bug, too.

All in all the Facebook Ad documentation is not as good as the Graph API reference.

**Comment by nbartels** [comment] 2015-11-21 12:15
I just opened a documentation issue for our own website and I'll try to add your information some how.

So I close this issue and mark it as `Question`.

**Closed by nbartels** 2015-11-21 12:15 UTC
Labels: type: question

**Comment by tezequiel** [comment] 2017-05-07 02:33
I could solve my issue thanks to this thread. I can confirm that `bytes` way works by Base64 encoding.

Thanks!
